POST http://localhost:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer 

{
  "title": "Test de Sara",
    "author": "Sara Bernal",
    "url": "https://reactpatterns.com/"
}
###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
"name":"Juan Diego Garzon Becerra",
"password": "sekret",
 "username": "jdiego"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"name":"Sara Bernal",
"password": "sekret",
 "username": "sbernal"
}
